{{- if eq .Values.mode "client" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcptunnel-config
data:
  config.yml: |
    server_addr: {{ .Values.server.remote_addr }}:{{ .Values.server.service.port }}
    {{- with .Values.tunnels }}
    tunnels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tcptunnel.fullname" . }}-client
  labels:
    {{- include "tcptunnel.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tcptunnel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tcptunnel.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tcptunnel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - client
            - -config=/tunnel/config/config.yml
            - -tls-crt=/tunnel/cert/tls.crt
            - -tls-key=/tunnel/cert/tls.key
            - -ca-crt=/tunnel/cert/tls.crt
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cert
              mountPath: /tunnel/cert
            - name: config
              mountPath: /tunnel/config
      volumes:
        - name: cert
          secret:
            secretName: tcptunnel-cert
            defaultMode: 420
        - name: config
          configMap:
            name: tcptunnel-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}