{{- if eq .Values.mode "server" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-tcp-tunnel.fullname" . }}-server
  labels:
    {{- include "go-tcp-tunnel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: tunnel
      protocol: TCP
      name: tunnel
    {{- with .Values.server.tunnelService }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "go-tcp-tunnel.selectorLabels" . | nindent 4 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-tcp-tunnel.fullname" . }}-server
  labels:
    {{- include "go-tcp-tunnel.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "go-tcp-tunnel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "go-tcp-tunnel.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "go-tcp-tunnel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - server
            - -addr=0.0.0.0:{{ .Values.server.service.port }}
            - -tls-crt=/tunnel/cert/tls.crt
            - -tls-key=/tunnel/cert/tls.key
            - -ca-crt=/tunnel/cert/tls.crt
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tunnel
              protocol: TCP
              containerPort: {{ .Values.server.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cert
              mountPath: /tunnel/cert
      volumes:
        - name: cert
          secret:
            secretName: go-tcp-tunnel-cert
            defaultMode: 420
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}