version: 2

before:
  hooks:
  - go mod download
builds:
- id: go-stream-tunnel
  main: ./cmd/go-stream-tunnel
  binary: go-stream-tunnel
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
archives:
- ids:
  - go-stream-tunnel
  name_template: "go-stream-tunnel_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  formats:
  - tar.gz
release:
  draft: true